name: Generate Terraform Docs

on:
  pull_request:
    branches: [main]
    paths:
      - "*.tf"
      - ".terraform-docs.yml"
      - ".github/workflows/terraform-docs.yml"

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: true
         
